[root]
generation = 8
last_updated = 1790707483
name = 'OneDrive:'

[[index]]
id = 0
parent = -1
name = ""
type = "root"

[[index]]
id = 1
parent = 0
name = "example.txt"
type = "file"
physical_address = "/path/to/file"